apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: desafio-devops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: desafio-devops/mysql
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: desafio-devops/mysql
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: desafio-devops/mysql
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: desafio-devops/mysql
        property: MYSQL_DATABASE
