server {
    listen 80;

    location = /nginx-health {
        access_log off;
        default_type text/plain;
        return 200 "OK";
    }

    location / {
        proxy_pass http://app:3000;
    }
}